export const legacyBuckets = [
  {
    name: 'Graph Mastery',
    description: 'Complete graph problems covering BFS, DFS, shortest paths, and more',
    category: 'graph',
    icon: 'Network',
    color: '#8B5CF6',
    problems: [
      { title: '111. Minimum Depth of Binary Tree', topic: 'BFS', difficulty: 'easy', problemLink: 'https://leetcode.com/problems/minimum-depth-of-binary-tree/', platform: 'leetcode', tags: ['bfs', 'tree'], order: 0 },
      { title: '752. Open the Lock', topic: 'BFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/open-the-lock/', platform: 'leetcode', tags: ['bfs', 'graph'], order: 1 },
      { title: '207. Course Schedule', topic: 'BFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/course-schedule/', platform: 'leetcode', tags: ['bfs', 'topological-sort', 'graph'], order: 2 },
      { title: '279. Perfect Squares', topic: 'BFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/perfect-squares/', platform: 'leetcode', tags: ['bfs', 'dp'], order: 3 },
      { title: '310. Minimum Height Trees', topic: 'BFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/minimum-height-trees/', platform: 'leetcode', tags: ['bfs', 'tree', 'graph'], order: 4 },
      { title: '785. Is Graph Bipartite?', topic: 'BFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/is-graph-bipartite/', platform: 'leetcode', tags: ['bfs', 'dfs', 'graph'], order: 5 },
      { title: '787. Cheapest Flights Within K Stops', topic: 'BFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/cheapest-flights-within-k-stops/', platform: 'leetcode', tags: ['bfs', 'dijkstra', 'dp'], order: 6 },
      { title: '133. Clone Graph', topic: 'BFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/clone-graph/', platform: 'leetcode', tags: ['bfs', 'dfs', 'graph'], order: 7 },
      { title: '199. Binary Tree Right Side View', topic: 'BFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/binary-tree-right-side-view/', platform: 'leetcode', tags: ['bfs', 'tree'], order: 8 },
      { title: '200. Number of Islands', topic: 'BFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/number-of-islands/', platform: 'leetcode', tags: ['bfs', 'dfs', 'matrix'], order: 9 },
      { title: '130. Surrounded Regions', topic: 'BFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/surrounded-regions/', platform: 'leetcode', tags: ['bfs', 'dfs', 'matrix'], order: 10 },
      { title: '934. Shortest Bridge', topic: 'BFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/shortest-bridge/', platform: 'leetcode', tags: ['bfs', 'dfs', 'matrix'], order: 11 },
      { title: '994. Rotting Oranges', topic: 'BFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/rotting-oranges/', platform: 'leetcode', tags: ['bfs', 'matrix'], order: 12 },
      { title: '1091. Shortest Path in Binary Matrix', topic: 'BFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/shortest-path-in-binary-matrix/', platform: 'leetcode', tags: ['bfs', 'matrix'], order: 13 },
      { title: '1129. Shortest Path with Alternating Colors', topic: 'BFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/shortest-path-with-alternating-colors/', platform: 'leetcode', tags: ['bfs', 'graph'], order: 14 },
      { title: '1519. Number of Nodes in the Sub-Tree With the Same Label', topic: 'BFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/number-of-nodes-in-the-sub-tree-with-the-same-label/', platform: 'leetcode', tags: ['bfs', 'dfs', 'tree'], order: 15 },
      { title: '116. Populating Next Right Pointers in Each Node', topic: 'BFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/populating-next-right-pointers-in-each-node/', platform: 'leetcode', tags: ['bfs', 'tree'], order: 16 },
      { title: '1765. Map of Highest Peak', topic: 'BFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/map-of-highest-peak/', platform: 'leetcode', tags: ['bfs', 'matrix'], order: 17 },
      { title: '127. Word Ladder', topic: 'BFS', difficulty: 'hard', problemLink: 'https://leetcode.com/problems/word-ladder/', platform: 'leetcode', tags: ['bfs', 'string'], order: 18 },
      { title: '827. Making A Large Island', topic: 'BFS', difficulty: 'hard', problemLink: 'https://leetcode.com/problems/making-a-large-island/', platform: 'leetcode', tags: ['bfs', 'dfs', 'matrix'], order: 19 },
      { title: '126. Word Ladder II', topic: 'BFS', difficulty: 'hard', problemLink: 'https://leetcode.com/problems/word-ladder-ii/', platform: 'leetcode', tags: ['bfs', 'backtracking'], order: 20 },
      { title: '847. Shortest Path Visiting All Nodes', topic: 'BFS', difficulty: 'hard', problemLink: 'https://leetcode.com/problems/shortest-path-visiting-all-nodes/', platform: 'leetcode', tags: ['bfs', 'bitmask', 'dp'], order: 21 },
      { title: '854. K-Similar Strings', topic: 'BFS', difficulty: 'hard', problemLink: 'https://leetcode.com/problems/k-similar-strings/', platform: 'leetcode', tags: ['bfs', 'string'], order: 22 },
      { title: '104. Maximum Depth of Binary Tree', topic: 'DFS', difficulty: 'easy', problemLink: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/', platform: 'leetcode', tags: ['dfs', 'tree'], order: 23 },
      { title: '112. Path Sum', topic: 'DFS', difficulty: 'easy', problemLink: 'https://leetcode.com/problems/path-sum/', platform: 'leetcode', tags: ['dfs', 'tree'], order: 24 },
      { title: '94. Binary Tree Inorder Traversal', topic: 'DFS', difficulty: 'easy', problemLink: 'https://leetcode.com/problems/binary-tree-inorder-traversal/', platform: 'leetcode', tags: ['dfs', 'tree'], order: 25 },
      { title: '79. Word Search', topic: 'DFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/word-search/', platform: 'leetcode', tags: ['dfs', 'backtracking', 'matrix'], order: 26 },
      { title: '98. Validate Binary Search Tree', topic: 'DFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/validate-binary-search-tree/', platform: 'leetcode', tags: ['dfs', 'tree', 'bst'], order: 27 },
      { title: '236. Lowest Common Ancestor of a Binary Tree', topic: 'DFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/', platform: 'leetcode', tags: ['dfs', 'tree'], order: 28 },
      { title: '417. Pacific Atlantic Water Flow', topic: 'DFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/pacific-atlantic-water-flow/', platform: 'leetcode', tags: ['dfs', 'bfs', 'matrix'], order: 29 },
      { title: '695. Max Area of Island', topic: 'DFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/max-area-of-island/', platform: 'leetcode', tags: ['dfs', 'bfs', 'matrix'], order: 30 },
      { title: '547. Number of Provinces', topic: 'DFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/number-of-provinces/', platform: 'leetcode', tags: ['dfs', 'union-find', 'graph'], order: 31 },
      { title: '210. Course Schedule II', topic: 'DFS', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/course-schedule-ii/', platform: 'leetcode', tags: ['dfs', 'topological-sort', 'graph'], order: 32 },
      { title: '332. Reconstruct Itinerary', topic: 'DFS', difficulty: 'hard', problemLink: 'https://leetcode.com/problems/reconstruct-itinerary/', platform: 'leetcode', tags: ['dfs', 'eulerian-path', 'graph'], order: 33 },
      { title: '124. Binary Tree Maximum Path Sum', topic: 'DFS', difficulty: 'hard', problemLink: 'https://leetcode.com/problems/binary-tree-maximum-path-sum/', platform: 'leetcode', tags: ['dfs', 'tree', 'dp'], order: 34 },
      { title: '743. Network Delay Time', topic: 'Shortest Path', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/network-delay-time/', platform: 'leetcode', tags: ['dijkstra', 'graph'], order: 35 },
      { title: '1334. Find the City With the Smallest Number of Neighbors', topic: 'Shortest Path', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/', platform: 'leetcode', tags: ['floyd-warshall', 'dijkstra', 'graph'], order: 36 },
      { title: '1514. Path with Maximum Probability', topic: 'Shortest Path', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/path-with-maximum-probability/', platform: 'leetcode', tags: ['dijkstra', 'graph'], order: 37 },
      { title: '778. Swim in Rising Water', topic: 'Shortest Path', difficulty: 'hard', problemLink: 'https://leetcode.com/problems/swim-in-rising-water/', platform: 'leetcode', tags: ['dijkstra', 'binary-search', 'matrix'], order: 38 },
      { title: '684. Redundant Connection', topic: 'Union Find', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/redundant-connection/', platform: 'leetcode', tags: ['union-find', 'graph'], order: 39 },
      { title: '721. Accounts Merge', topic: 'Union Find', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/accounts-merge/', platform: 'leetcode', tags: ['union-find', 'dfs'], order: 40 },
      { title: '1202. Smallest String With Swaps', topic: 'Union Find', difficulty: 'medium', problemLink: 'https://leetcode.com/problems/smallest-string-with-swaps/', platform: 'leetcode', tags: ['union-find', 'sorting'], order: 41 },
    ],
  },
];
